# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ms-sql-server:
    image: leonardomendes/dbapiuser:sqlserver
    container_name: dbsqlserver
    environment: 
      SA_PASSWORD: "Leonardo@321"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - 1433:1433
  userapi:
    image: apiuser
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80